version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_nariman
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: checklist_db
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/app/migrations

  backend:
    build: ./src/index.ts
    container_name: backend_nariman
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: checklist_db
    depends_on:
      - postgres
    
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/checklist_db
    command: > 
        sh -c "npx tsx src/run_migrations.ts && npx tsx src/index.ts"
    volumes:
        - ./migrations:/app/migrations